apiVersion: apps/v1               # Apps API group, v1 version
kind: Deployment                  # Creates and manages pods
metadata:
  name: wil-playground           # Deployment name
  namespace: dev                 # Which namespace to deploy in
  labels:
    app: playground
    version: v1
spec:                            # Desired state specification
  replicas: 1                    # How many pod instances
  selector:                      # How deployment finds its pods
    matchLabels:
      app: playground
  template:                      # Pod template
    metadata:
      labels:
        app: playground          # Pod labels (must match selector)
    spec:                        # Pod specification
      containers:                # List of containers in pod
      - name: playground         # Container name
        image: broly20/flask-app-p3:v1  # Docker image to run
        ports:
        - containerPort: 5000    # Port the app listens on
        resources:               # Resource limits/requests
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"