apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: t2o-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/RIDWANE-EL-FILALI/iot-rel-fila'
    targetRevision: HEAD
    path: '.'
    directory:
      recurse: true
      include: '*.yaml'  # Only include YAML files
      exclude: '{argocd-app.yaml,argocd-nodeport.yaml}'  # Exclude ArgoCD files
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
