apiVersion: apps/v1
kind: Deployment
metadata:
  name: t2o-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t2o-app
  template:
    metadata:
      labels:
        app: t2o-app
    spec:
      containers:
        - name: t2o-app
          image: broly20/flask-app-p3:v1
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: t2o-service
  namespace: dev
spec:
  selector:
    app: t2o-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000       # Cluster port
      targetPort: 5000 # Container port
      nodePort: 30001  # Exposed on localhost

